# 异常处理  
## 异常概述  
### 异常与错误  
- Exception(异常):可能发生的,经过处理后可以恢复正常的事件,如IOException。  
- Error(错误):致命的  

Java中异常也是对象,它继承自Throwable及其子类。Exception和Error都是Throwable的子类。  
常见异常:数学运算异常,数组下标越界异常,内存溢出异常  

### 标准异常类  
- 程序不能抛出Error。  
- 不受检查异常:被认为是可以合理发生的异常,是可以从逻辑层面上避免的。  
- 受检异常:强制程序员捕获的异常。 

## 异常处理方法  
### try-catch-finally  
格式:
```java
try{

}catch(异常类型|异常变量名){
	//异常处理代码
}finally{
	//方法返回之前总要执行的代码
}
```
- catch带一个Throwable类型的参数,代表它可以捕获的异常。catch块可以有多个,每个负责处理一种异常。
- finally:不管try是否发生异常,finally总是会在方法返回前执行。  

- try...catch...finally均不能单独使用。其中finally最多只能有一个,catch可以有多个。  
- 三个语句块分别独立而不能相互访问。  
- 当使用多个catch时,只会从前到后匹配第一个异常。所以假如要同时使用超类异常和子类异常,要把子类异常放在前面。

---
- Throwable提供了三个方法来获取异常和错误的信息。  
&emsp;1.getMessage()获取详细消息字符串  
&emsp;2.toString()获取简短的描述  
&emsp;3.printStackTrace()打印类型、性质栈层次以及在程序中出现的位置  
程序示例:  
```java
public class Main{
	public static void main(String[] args){
		try{
			System.out.println(1/0);
		}catch(Exception e){
			System.out.println(e.getMessage());
			System.out.println("\n");
			System.out.println(e.toString());
			System.out.println("\n");
			e.printStackTrace();
		}
	}
}
```

### 异常的抛出  
Java允许异常不在当前语句块内处理,而是将其抛出,送交至调用它的方法进行处理。也就是说,该方法不对异常进行处理,而是交由上一级的方法来catch。  
<a style="color:red">!!</a> 异常逐层上抛会消耗大量资源,所以要尽量自己处理能处理的异常,而不要交给上级方法。  

### 异常处理原则  
- 能处理的异常尽早处理  
- 对于受检异常,如果不能处理,则可以转换为RuntimeError抛出。  
- 对于一个应用程序来说,应该有一套自己的异常处理框架。  

## 自定义异常  
```java
public class MyException extends Exception{
	public MyException(String ErrorMessage){
		super(ErrorMessege);
	}
}
```

### 抛出异常对象
在方法中使用throw子句可以显式的产生并抛出异常。语法如下:
```java
throw new MyException();
```

### throws和throw比较  
- throws用于声明该方法可能会抛出哪些异常  
- throw用于抛出异常  

### 异常转型  
将异常包装成其他类型的异常再抛出  
```java
try{
	...
}catch (IOException a){
	throw new Myexception();
}
```